name: Build test For MI5X(tiffany))

on:
  workflow_dispatch:

jobs:
  TwilightForTiffany:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full
          sudo apt clean
      - name: Cloning Sources and Toolchain
        run: |
          git clone https://github.com/windbell-project/android_kernel_xiaomi_msm8953.git -b lineage-19.1 --depth=1 --recurse-submodules android_kernel_xiaomi_msm8953
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r445002 --depth=1 --single-branch --no-tags -b 12.0 ~/clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
          git clone -b tiffany https://github.com/Tkiliay/AnyKernel3.git -b tiffany
      - name: Applying Kernel Patch
        run: |
           cd android_kernel_xiaomi_msm8953/KernelSU
           wget https://github.com/SakuraNotStupid/KernelSU/commit/7a6f621bfec513732bc97260186a89a79ff66387.patch
           patch -p1 < 7a6f621bfec513732bc97260186a89a79ff66387.patch
           rm -rf *.patch
      - name: Compiling Kernel(LineageOS)
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd android_kernel_xiaomi_msm8953
          make O="$output_dir" \
                      lineage_tiffany_defconfig
          make -j $(nproc) \
                       O="$output_dir" \
                       CC=clang
          popd
      - name: Packaging the Kernel
        run: |
          cp -v android_kernel_xiaomi_msm8953/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../Kernel-tiffany-AOSP.zip *
          popd
      - name: Creating Config Info
        run: |
          echo "Device: MI 5X
          Code: Tiffany
          Build Code: ${{ github.run_number }}
          Twilight Kernel For MI 5X" >> INFO.txt
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: Twilight_KernelSU-V1-CI-${{ env.BUILD_TIME }}-tiffany-AOSP.zip
          name: "Twilight_KernelSU-V1-tiffany_CI-${{ env.BUILD_TIME }}"
          tag: " ${{ env.BUILD_TIME }}_MI5X_CI_${{ github.run_number }}"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
